name: Units CI

on: [push, pull_request]

jobs:
  test:
    name: Test QA
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: npm i
      - run: npm run test-coverage
